//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterRobot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlreadyFollowed
    {
        public long twitterID { get; set; }
        public string twitterName { get; set; }
        public System.DateTime followDate { get; set; }
    }
}
